### PR TITLE
fix update-docs no refresh content after first run

### PR DESCRIPTION
**Pull request by dogoku**
Was caused by a missing `S`

I fixed the typo and updated the regex to cater for people that already run this command

### CODE REVIEW

**Comment by dogoku** [comment]
I opened the tests before submitting, saw QUnit, then closed them.
I guess today is the day I learn QUnit.

**Comment by rwjblue** [comment]
Hehe, it is a good day indeed! Thank you for working on this 😃

**Comment by dogoku** [comment]
Em, these tests are quite complex, with all the directory setup, so it's taking a lot long that what I expected.

I'm gonna have to add the test next week, because I was in the middle of writing codemods and I only have the weekend to finish them.

**Comment by rwjblue** [comment]
Gotcha! Thanks for trying, and I’m sorry it turned into a hassle...

**Pull request merged**
