### PR TITLE
Add two tests for experimental class/decorators

### PR DESCRIPTION
**Pull request by allthesignals**
This PR adds two new tests for class and decorator syntax, including with TypeScript.

### CODE REVIEW

**Comment by allthesignals** [comment]
(Tests pass locally for me, not sure how to debug)

**Comment by rwjblue** [comment]
The issue with the "floating dependencies" job is https://github.com/babel/babel/issues/8277.

An updated `@babel/parser` was released that requires some additional config (though it isn't 100% clear what just yet), and that `floating dependencies` job specifically does `yarn install --no-lockfile`.

**Comment by rwjblue** [comment]
I submitted https://github.com/benjamn/recast/pull/521 to fix the error upstream in recast, and https://github.com/rwjblue/codemod-cli/pull/40 to work around it in codemod-cli for now.

**Comment by rwjblue** [comment]
Thank you!

**Pull request merged**
